routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');
Route::get('perfil/informacion_editar',['as'=> 'perfil.edit', 'uses' => 'UsersController@edit']);
Route::put('perfil/informacion_editar',['as'=> 'perfil.update', 'uses' => 'UsersController@update']);
Route::resource('/paciente', 'PacientesController');
route::resource('/usuarios', 'InformacionesController');
Route::resource('/tratamiento', 'TratamientosController');
Route::resource('/evaluacion', 'RegistroController');
Route::get('/tratamiento_lista', 'TratamientosController@tratamiento_lista');
Route::get('paciente/pdfexport/{paciente}', 'PacientesController@pdfexport');
Route::get('evaluacion/pdfexport/{evaluacion}', 'RegistroController@pdfexport');


// PDF

// Route::get('pdf', function() {
//     $users = App\Paciente::find($id);
//     $pdf = PDF::loadview('ejemplo', ['paciente' => $users]);
//     return $pdf->download('ejemplo.pdf');
// });

resources/views/Evaluacion/evaluacion_crear.blade.php
<script src="http://code.jquery.com/jquery-latest.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    /**
     * Funcion para añadir una nueva fila en la tabla
     */
    var cont = 0;
    $("#add").click(function() {
        cont++;
        var nuevaFila = "<tr> \
			  //<td><input type='text' name='palabras[" + cont + "][estimulo]'></td> \
                <td><input type='text' name='palabras[" + cont + "][fonema]'></td> \
                <td><input type='text' name='palabras[" + cont + "][inicial]'></td> \
                <td><input type='text' name='palabras[" + cont + "][media]'></td> \
                <td><input type='text' name='palabras[" + cont + "][final]'></td> \
                <td><input type='text' name='palabras[" + cont + "][transicion]'></td> \
                <td><input type='text' name='palabras[" + cont + "][respuesta]'></td> \
				<td><input type='button' class='del' value='Eliminar Fila'></td> \
			</tr>";
        $("#tabla tbody").append(nuevaFila);
    });

    // evento para eliminar la fila
    $("#tabla").on("click", ".del", function() {
        $(this).parents("tr").remove();
    });

    $("#add").click();
});
</script>

<script type="text/javascript">
$(document).ready(function() {
    /**
     * Funcion para añadir una nueva fila en la tabla
     */
    var cont = 0;
    $("#add1").click(function() {
        cont++;
        var nuevaFila = "<tr> \
			  //<td><input type='text' name='diptongos[" + cont + "][diptongo]'></td> \
                <td><input type='text' name='diptongos[" + cont + "][estimulod]'></td> \
                <td><input type='text' name='diptongos[" + cont + "][respuestad]'></td> \
                <td><input type='text' name='diptongos[" + cont + "][transiciond]'></td> \
				<td><input type='button' class='del' value='Eliminar Fila'></td> \
			</tr>";
        $("#tabla1 tbody").append(nuevaFila);
    });

    // evento para eliminar la fila
    $("#tabla1").on("click", ".del", function() {
        $(this).parents("tr").remove();
    });

    $("#add1").click();
});
</script>
<script type="text/javascript">
$(document).ready(function() {
    /**
     * Funcion para añadir una nueva fila en la tabla
     */
    var cont = 0;
    $("#add2").click(function() {
        cont++;
        var nuevaFila = "<tr> \
			  //<td><input type='text' name='difonos[" + cont + "][difonos]'></td> \
                <td><input type='text' name='difonos[" + cont + "][estimulodf]'></td> \
                <td><input type='text' name='difonos[" + cont + "][respuestadf]'></td> \
                <td><input type='text' name='difonos[" + cont + "][transiciondf]'></td> \
				<td><input type='button' class='del' value='Eliminar Fila'></td> \
			</tr>";
        $("#tabla2 tbody").append(nuevaFila);
    });

    // evento para eliminar la fila
    $("#tabla2").on("click", ".del", function() {
        $(this).parents("tr").remove();
    });

    $("#add2").click();
});
</script>

<script type="text/javascript">
$(document).ready(function() {
    /**
     * Funcion para añadir una nueva fila en la tabla
     */
    var cont = 0;
    $("#add3").click(function() {
        cont++;
        var nuevaFila = "<tr> \
			  //<td><input type='text' name='silabas[" + cont + "][silabas]'></td> \
                <td><input type='text' name='silabas[" + cont + "][estimulods]'></td> \
                <td><input type='text' name='silabas[" + cont + "][respuestads]'></td> \
                <td><input type='text' name='silabas[" + cont + "][transicionds]'></td> \
				<td><input type='button' class='del' value='Eliminar Fila'></td> \
			</tr>";
        $("#tabla3 tbody").append(nuevaFila);
    });

    // evento para eliminar la fila
    $("#tabla3").on("click", ".del", function() {
        $(this).parents("tr").remove();
    });

    $("#add3").click();
});
</script>
<style>
table {
    margin-left: 0%;
    width: 100%;
    color: black;
    text-align: center;
    border-collapse: collapse;
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;

}

table th {
    font-size: 13px;
    font-weight: normal;
    padding: 8px;
    color: white;
    background: #3490dc !important;
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;

}
input {
        border-radius: 2px;
        outline: none;
        border: 1px solid #ccc;
        width: 100%;
    }

table td {
    text-align: center;
    opacity: 0.8;
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: 400; line-height: 18.5714px;

}

</style>

@section('title', "Centro de Salud")
@section('name', "Home")


@extends('layouts.app1')

@yield('sidebar')
@section('content')

<div class="container">
    <br><br>
    
        <form action="{{ route('evaluacion.store')}}" method="POST">
            @method('post')
            @csrf
            <h1>REGISTRO DE EVALUACIÓN</h1>



            @if (count($errors) > 0)


            <div class="alert alert-danger">
                <div>
                    <ul>
                        @foreach ($errors->all() as $message)
                        <h6><error>Error!</strong> {{ $message }}</h6>
                        @endforeach
                    </ul>
                </div>
            </div>
            @endif
            
            <div class="form-row">
            <div class="col">
                <h4>Paciente </h4>
                <select class="form-control" name="id_p">
                    <option value="">--NINGUNO--</option>
                    @foreach ($groups as $group)
                    <option value="{{$group->id}}">{{ $group->nombre }}</option>
                    @endforeach
                </select>
                </div>
                <div class="col">
                <h4>Fecha de Evaluación</h4>
                <input type="date" name="fecha" class="form-control" placeholder="Fecha de Evaluacion">
                </div>
            </div><br>

        <table id="tabla">
            <thead>
                <tr>
                    <!-- <th>Cedula</th> -->
                    <th>Estímulo</th>
                    <th>Fonema</th>
                    <th>Inicial</th>
                    <th>Media</th>
                    <th>Final</th>
                    <th>Transcripción</th>
                    <th>Respuesta</th>

                    <th><input type="button" id="add" value="añadir fila"></th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table><br>
        <table id="tabla1">
            <thead>
                <tr>
                    <!-- <th>Cedula</th> -->
                    <th>Diptongos</th>
                    <th>Estímulo</th>
                    <th>Respuesta</th>
                    <th>Transcripción</th>

                    <th><input type="button" id="add1" value="añadir fila"></th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table><br>
        <table id="tabla2">
            <thead>
                <tr>
                    <!-- <th>Cedula</th> -->
                    <th>Dífonos</th>
                    <th>Estímulo</th>
                    <th>Respuesta</th>
                    <th>Transcripción</th>

                    <th><input type="button" id="add2" value="añadir fila"></th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table><br>
        <table id="tabla3">
            <thead>
                <tr>
                    <!-- <th>Cedula</th> -->
                    <th>Inversas</th>
                    <th>Estímulo</th>
                    <th>Respuesta</th>
                    <th>Transcripcion</th>

                    <th><input type="button" id="add3" value="añadir fila"></th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table><br>


            <div class="form-row">
                <div class="col">
                    <input type="int" name="observacion" class="form-control" placeholder="Observación">
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <input type="int" name="recomendacion" class="form-control" placeholder="Recomendación">
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <input type="int" name="conclusion" class="form-control" placeholder="Conclusión">
                </div>
            </div>


            <div class="contenedor">
                <br>
                <div class="row justify-content-md-center">
                    <div class="col-4">
                        <input title="GUARDAR" type=image src="/images/guardar.png" width="50" height="50"
                            class="imagenpequeña">
                        <h5>Guardar</h5>

                    </div>
                    <div class="col-4">
                        <a title="CANCELAR" href="/evaluacion"><img src="/images/cancelar.png" class="pequeña"></a>
                        <h5>Cancelar</h5>
                    </div>
                </div>


        </form>
    


</div>
@endsection

resources/views/Evaluacion/evaluacion_lista.blade.php
@section('title', "Centro de Salud")
@section('name', "Home")

@extends('layouts.app1')
@yield('sidebar')
@section('content')

<div class="container">
    <br><br>
    <h1>EVALUACIONES DE PACIENTES</h1>


    <a title="Nuevo Tratamiento" href="{{ route('evaluacion.create')}}"><img src="/images/evaluacion.png" class="imagenpequeña1"></a>
    <!-- <h5>Crear Evaluación</h5> -->
    <h5>
        <a title="Nuevo Tratamiento" href="{{ route('evaluacion.create')}}">Crear Tratamiento</a>
    </h5>

    <form>
        <div class="card-body row no-gutters align-items-center">
            <!--end of col-->
            <div class="col">
                <input class="form-control form-control-lg form-control-borderless" type="search"
                    placeholder="Buscar" name="search" id="search">
            </div>
            <!--end of col-->
            <div class="col-auto">
                <button class="btn btn-lg btn-success" type="submit">Buscar</button>
            </div>
            <!--end of col-->
        </div>
    </form>

</div><br>
<div class="table-responsive1">
    <table class="table small">
        <thead>
            <tr class="table-secondary">
            <th>Id</th>
            <th>Paciente</th>
            <th>Fecha</th>
            <th>Observación</th>
            <th>Recomendación</th>
            <th>Conclusión</th>
           
            <!-- <th>TERAPEUTA</th> -->
            <th>Opciones</th>
            </tr>
        </thead>
        @forelse($evaluacion  as $evaluacio)
        <tr>
            <td>{{ $evaluacio->id }}
            <td>{{ $evaluacio->paciente->nombre }}</td>
            <td>{{ $evaluacio->fecha }}</td>
            <td>{{ $evaluacio->observacion }}</td>
            <td>{{ $evaluacio->recomendacion }}</td>
            <td>{{ $evaluacio->conclusion }}</td>
            <td>
                <div class="container">
                    <div class="row justify-content-md-center">
                        <div class="col-">
                        <a title="Editar" href="{{route('evaluacion.edit', $evaluacio->id)}}"><img src="/images/editar.png"
                        class="imagenpequeña"></a>
                        </div>
                        <div class="col-">
                        <a title="PDF" href="{{ url('evaluacion/pdfexport/' . $evaluacio->id)}}" target="_blank"><img
                                src="/images/pdf.png" class="imagenpequeña"></a>
                        </div>
                        <div class="col-">
                        <form action="{{route('evaluacion.destroy', $evaluacio->id)}}" method="post">
                                @method('delete')
                                @csrf
                                <input title="Eliminar" type=image src="/images/eliminar.png" width="50" height="50"
                                    class="imagenpequeña"> </form>
                        </div>
                    </div>
                </div>
            </td>


        </tr>

        @empty


        <h5>No existe evaluaciones registradas</h5>

        @endforelse


    </table>
    <div class="paginate">
    {{$evaluacion->links()}}
    </div>

</div>



</div>
@endsection

resources/views/Evaluacion/pdf.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>

<style>
h1 {
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
    text-align: center;
}

h2 {
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
    text-align: center;
}

h3 {
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
    text-align: center;
}

h4 {
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
    text-align: center;
}

p {
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;

}

table {
    width: 100%;
    color: black;
    text-align: center;
    border-collapse: collapse;
    border: solid 1px #000000;
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;

}

table th {
    font-size: 13px;
    font-weight: normal;
    padding: 0px;
    color: black;
    border-top: 0px solid black;
    border-bottom: 1px solid black;

    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;

}
label{
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
line-height: 20pt;        /* para la separacion entre lineas */ 
text-indent: 30pt;        /* para sangrias */ 
}

/* Configuracion para la paginacion */
#header,
#footer {
  position: fixed;
  left: 0;
	right: 0;
	color: #aaa;
	font-size: 0.9em;
}
#header {
  top: 0;
	border-bottom: 0.1pt solid #aaa;
}
#footer {
  bottom: 0;
  border-top: 0.1pt solid #aaa;
}
.page-number:before {
  content: "Page " counter(page);
}

.left{
    float: left;
    
}

.center{
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
    text-align: center;
    font-size: 200%;
    }

img.pequeña {
    width: 30px;
    height: 30px;
    margin: auto;
    display: block;
}

#inferior{
position:absolute; /*El div será ubicado con relación a la pantalla*/
left:0px; /*A la derecha deje un espacio de 0px*/
right:0px; /*A la izquierda deje un espacio de 0px*/
bottom:100px; /*Abajo deje un espacio de 0px*/
height:0px; /*alto del div*/
z-index:0;
 }

</style>


<body>
<p>
<div class="left" id="center" class="pequeña">
<img src="{{ public_path('images/sigsig_logo.png') }}" class="pequeña">
</div>
<div class="center" id="center">
<!-- CENTRO DIURNO DE CUIDADO Y DESARROLLO INTEGRAL PARA PERSONAS CON DISCAPACIDAD -->
CENTRO DIURNO DE CUIDADO Y DESARROLLO INTEGRAL
</div>


<h2>EVALUACIÓN DE PACIENTE</h2><br>
<label>Paciente: </label>{{$pacientes->nombre}}<br>
<label>Fecha de Evaluación: </label>{{$evaluacion->fecha}}<br><br>


<!-- <label>Fecha de Nacimiento: </label>{{$pacientes->f_nacimiento}}<br> -->



<h4>ESTÍMULO</h4>
<table id="tabla">
            <thead>
                <tr>
                    <th>Estímulo</th>
                    <th>Fonema</th>
                    <th>Inicial</th>
                    <th>Media</th>
                    <th>Final</th>
                    <th>Transición</th>
                    <th>Respuesta</th>
                </tr>
            </thead>

            <tbody>
                @foreach($evaluacion->palabras as $palabra)
                
                <tr>
                    <td>{{$palabra->estimulo}}</td>
                    <td>{{$palabra->fonema}}</td>
                    <td>{{$palabra->inicial}}</td>
                    <td>{{$palabra->media}}</td>
                    <td>{{$palabra->final}}</td>
                    <td>{{$palabra->transicion}}</td>
                    <td>{{$palabra->respuesta}}</td>
                    
                </tr>
                @endforeach
                

            </tbody>

        </table>

        <h4>DIPTONGOS</h4>
        <table id="tabla1">
            <thead>
                <tr>
                    <th>Diptongos</th>
                    <th>Estímulo</th>
                    <th>Respuesta</th>
                    <th>Transcripción</th>

                </tr>
            </thead>

            <tbody>
                @foreach($evaluacion->diptongos as $diptongo)
                <tr>
                    <td>{{$diptongo->diptongo}}</td>
                    <td>{{$diptongo->estimulod}}</td>
                    <td>{{$diptongo->respuestad}}</td>
                    <td>{{$diptongo->transiciond}}</td>
                </tr>
                @endforeach

            </tbody>

            </table><br>
            
            <h4>DIFONOS</h4>
            <table id="tabla2">
            <thead>
                <tr>
                    <th>Difonos</th>
                    <th>Estímulo</th>
                    <th>Respuesta</th>
                    <th>Transcripción</th>
                </tr>
            </thead>

            <tbody>
                @foreach($evaluacion->difonos as $difono)
                <tr>
                    <td>{{$difono->difonos}}</td>
                    <td>{{$difono->estimulodf}}</td>
                    <td>{{$difono->respuestadf}}</td>
                    <td>{{$difono->transiciondf}}</td>
                </tr>
                @endforeach

            </tbody>
            </table>


                    <!-- TABLA 4 Diptongos -->

                    <h4>SILABAS INVERSAS</h4>
        <table id="tabla3">
            <thead>
                <tr>
                    <th>Inversa</th>
                    <th>Estímulo</th>
                    <th>Respuesta</th>
                    <th>Transcripción</th>

                </tr>
            </thead>

            <tbody>
                @foreach($evaluacion->silabasinversas as $silabasinversa)
                <tr>
                    <td>{{$silabasinversa->silabas}}</td>
                    <td>{{$silabasinversa->estimulods}}</td>
                    <td>{{$silabasinversa->respuestads}}</td>
                    <td>{{$silabasinversa->transicionds}}</td>
                </tr>
                @endforeach

            </tbody>

            </table>

            <br><br><br><br>

       

        <label>Observación:</label>
        {{$evaluacion->observacion}}<br>
        <label>Recomendación:</label>
        {{$evaluacion->recomendacion}}<br>
        <label>Conclusión:</label>
        {{$evaluacion->conclusion}}<br><br><br>


       
        

        <div id="inferior">
        <h4>___________________________</h4>
        <h4>{{ Auth::user()->name }}</h4>
        </div>

</p>

{{-- Here's the magic. This MUST be inside body tag. Page count / total, centered at bottom of page --}}
<script type="text/php">
    if (isset($pdf)) {
        $text = "page {PAGE_NUM} / {PAGE_COUNT}";
        $size = 10;
        $font = $fontMetrics->getFont("Verdana");
        $width = $fontMetrics->get_text_width($text, $font, $size) / 2;
        $x = ($pdf->get_width() - $width) / 2;
        $y = $pdf->get_height() - 35;
        $pdf->page_text($x, $y, $text, $font, $size);
    }
</script>
</body>