routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');
Route::get('perfil/informacion_editar',['as'=> 'perfil.edit', 'uses' => 'UsersController@edit']);
Route::put('perfil/informacion_editar',['as'=> 'perfil.update', 'uses' => 'UsersController@update']);
Route::resource('/paciente', 'PacientesController');
route::resource('/usuarios', 'InformacionesController');
Route::resource('/tratamiento', 'TratamientosController');
Route::resource('/evaluacion', 'RegistroController');
Route::get('/tratamiento_lista', 'TratamientosController@tratamiento_lista');
Route::get('paciente/pdfexport/{paciente}', 'PacientesController@pdfexport');
Route::get('evaluacion/pdfexport/{evaluacion}', 'RegistroController@pdfexport');


// PDF

// Route::get('pdf', function() {
//     $users = App\Paciente::find($id);
//     $pdf = PDF::loadview('ejemplo', ['paciente' => $users]);
//     return $pdf->download('ejemplo.pdf');
// });

app/Http/Controllers/TratamientosController.php
<?php

namespace App\Http\Controllers;

use App\Terapia;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use Storage;
use DB;

class TratamientosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {   
        // $tratamientos = DB::table('terapias')->get();
        // $tratamientos= Terapia::name($request->get('search'))->orderBy('id')
        $tratamientos = Terapia::name($request->get('search'))->with('users')->where('id_u', Auth::id())->orderBy('id')
        ->paginate(6);
        return view('Tratamiento/tratamiento',compact('tratamientos'));
    }

     public function tratamiento_lista(Request $request)
    {
        //
        // $tratamientos = Terapia::paginate(6);
        $tratamientos = Terapia::name($request->get('search'))->with('users')->where('id_u', Auth::id())->paginate(5);
        $title = "Listado de Registros";

        return view('Tratamiento/tratamiento_lista', compact('title', 'tratamientos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('Tratamiento/tratamiento_crear');
    }
   
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules= [
            'imagen' => 'required',
            'palabra' => 'required',
        ];

        $this->validate($request, $rules);
        
        if($name = $request->file('audio')){
            $file=$request->file('audio');
           $name=time().$file->getClientOriginalName();
           $file->move(public_path().'/sound/', $name);
           
         }        
         
        if($img = $request->file('imagen')){
            $file=$request->file('imagen');
           $img=time().$file->getClientOriginalName();
           $file->move(public_path().'/imagen/', $img);
           
         }        
           
         $tratamiento = new Terapia();
        
          
           $tratamiento->palabra = $request->palabra;
           $tratamiento->audio = $name;
           $tratamiento->imagen = $img;
           $tratamiento->id_u = Auth::user()->id;
           
        //    $img = $request->file('imagen');

        //    $file_route = time().'_'.$img->getClientOriginalName();
        //    Storage::disk('imagen')->put($file_route,file_get_contents($img->getRealPath()));
           
    
           if($tratamiento->save()){
           return redirect()->route('tratamiento.index')->with('exito',"REGISTRO GUARDADO EXITOSAMENTE");
           }else{
               return redirect()->route('tratamiento.index')->with('error',"ERROR AL GUARDAR UN PACIENTE");
         }
     }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tratamiento  $tratamiento
     * @return \Illuminate\Http\Response
     */
    public function show(Terapia $tratamiento)
    {
        //
        return view('Tratamiento/tratamiento_show', compact('tratamientos'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tratamiento  $tratamiento
     * @return \Illuminate\Http\Response
     */
    public function edit(Terapia $tratamiento)
    {
        //
        return view('Tratamiento/tratamiento_editar', compact('tratamiento'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tratamiento  $tratamiento
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Terapia $tratamiento)
    {
        $rules= [
            'imagen' => 'required',
            'palabra' => 'required',
        ];

        $this->validate($request, $rules);


        $tratamiento->fill($request->except('imagen','audio'));
        if($name = $request->file('audio')){
            $file=$request->file('audio');
           $name=time().$file->getClientOriginalName();
           $tratamiento->audio = $name;
           $file->move(public_path().'/sound/', $name);
           
         }        
         
        if($img = $request->file('imagen')){
            $file=$request->file('imagen');
           $img=time().$file->getClientOriginalName();
           $tratamiento->imagen = $img;
           $file->move(public_path().'/imagen/', $img);
           
         }        
        
    
           if($tratamiento->update()){
        return redirect()->route('tratamiento.index')->with('exito',"TRATAMIENTO GUARDADO EXITOSAMENTE");
           }else{
               return redirect()->route('tratamiento.index')->with('error',"ERROR AL GUARDAR TRATAMIENTO");
         }
           
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tratamiento  $tratamiento
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $tratamiento = Terapia::find($id)->delete();
        return redirect()->route('tratamiento.index')->with('exito',"Eliminado Exitoso");

    }
    }

resources/views/Tratamiento/tratamiento.blade.php
@section('title', "Centro de Salud")
@section('name', "Home")

@extends('layouts.app1')
@yield('sidebar')
@section('content')

<div class="container">
    <br><br>
    <h1>TRATAMIENTOS</h1>

    <form>
        <div class="card-body row no-gutters align-items-center">
            <!--end of col-->
            <div class="col">
                <input class="form-control form-control-lg form-control-borderless" type="search" placeholder="Buscar"
                    name="search" id="search">
            </div>
            <!--end of col-->
            <div class="col-auto">
                <button class="btn btn-lg btn-success" type="submit">Buscar</button>
            </div>
            <!--end of col-->
        </div>
    </form>

    <div class="row">
        @foreach($tratamientos as $tratamiento)
        <div class="col-sm">
            <div class="card" style="width: 20rem; height:">
                <img src="imagen/{{$tratamiento->imagen}}" class="card-img-top" alt="..." width="304" height="236">
                <div class="card-body">
                    <h5 class="card-title" >{{$tratamiento->palabra}}</h5>
                    <p class="card-text"></p>
                    <audio controls="controls">
                        <source src="sound/{{$tratamiento->audio}}" type="audio/ogg" />
                        <source src="sound/{{$tratamiento->audio}}" type="audio/mpeg" />
                    </audio>
                </div>
               
            </div>
            <br>
        </div>
        @endforeach

    </div>
    <div class="paginate">
    {{$tratamientos->links()}}
    </div>

</div>
@endsection

resources/views/Tratamiento/tratamiento_crear.blade.php
<style>
@import url(https://fonts.googleapis.com/css?family=Roboto:300);

.login-page {
    width: 360px;
    padding: 8% 0 0;
    margin: auto;
}

.form {
    position: relative;
    z-index: 1;
    background: #FFFFFF;
    max-width: 360px;
    margin: 0 auto 100px;
    padding: 30px;
    text-align: center;
    box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}

.form input {
    font-family: "Roboto", sans-serif;
    outline: 0;
    background: #f2f2f2;
    width: 100%;
    border: 0;
    margin: 0 0 15px;
    padding: 15px;
    box-sizing: border-box;
    font-size: 14px;
}

.form button {
    font-family: "Roboto", sans-serif;
    text-transform: uppercase;
    outline: 0;
    background: #3490dc;
    width: 100%;
    border: 0;
    padding: 15px;
    color: #FFFFFF;
    font-size: 14px;
    -webkit-transition: all 0.3 ease;
    transition: all 0.3 ease;
    cursor: pointer;
}

.form button:hover,
.form button:active,
.form button:focus {
    background: #43A047;
}

.form .message {
    margin: 15px 0 0;
    color: #b3b3b3;
    font-size: 12px;
}

.form .message a {
    color: #4CAF50;
    text-decoration: none;
}

.form .register-form {
    display: none;
}

.container:before,
.container:after {
    content: "";
    display: block;
    clear: both;
}

.container .info {
    margin: 50px auto;
    text-align: center;
}

.container .info h1 {
    margin: 0 0 15px;
    padding: 0;
    font-size: 36px;
    font-weight: 300;
    color: #1a1a1a;
}

.container .info span {
    color: #4d4d4d;
    font-size: 12px;
}

.container .info span a {
    color: #000000;
    text-decoration: none;
}

.container .info span .fa {
    color: #EF3B3A;
}

</style>


@section('title', "Centro de Salud")
@section('name', "Home")

@extends('layouts.app1')
@yield('sidebar')
@section('content')

<div class="container">
<form action="{{ route('tratamiento.store') }}" method="POST" enctype="multipart/form-data">
@method('post')
        {{@csrf_field()}}
        <h1>REGISTRO DE TRATAMIENTO</h1>

        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <div>
                    <ul>
                        @foreach ($errors->all() as $message)
                        <h6><error>Error!</strong> {{ $message }}</h6>
                        @endforeach
                    </ul>
                </div>
            </div>
            @endif

        <div class="login-page">
            <div class="form">
                <h2>Material Tratamiento</h2>
                <form class="register-form">
                    <h4>Imagen</h4>
                    <input type="file" name="imagen"><br>
                    <h4>Palabra</h4>
                    <input type="text" name="palabra"><br>
                    <h4>Audio</h4>
                    <input type="file" name="audio"><br>
                    <button>Guardar</button>
                </form>

            </div>
        </div>
    </form>
</div>
@endsection

resources/views/Tratamiento/tratamiento_editar.blade.php
<style>
@import url(https://fonts.googleapis.com/css?family=Roboto:300);

.login-page {
    width: 360px;
    padding: 8% 0 0;
    margin: auto;
}

.form {
    position: relative;
    z-index: 1;
    background: #FFFFFF;
    max-width: 360px;
    margin: 0 auto 100px;
    padding: 30px;
    text-align: center;
    box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}

.form input {
    font-family: "Roboto", sans-serif;
    outline: 0;
    background: #f2f2f2;
    width: 100%;
    border: 0;
    margin: 0 0 15px;
    padding: 15px;
    box-sizing: border-box;
    font-size: 14px;
}

.form button {
    font-family: "Roboto", sans-serif;
    text-transform: uppercase;
    outline: 0;
    background: #3490dc;
    width: 100%;
    border: 0;
    padding: 15px;
    color: #FFFFFF;
    font-size: 14px;
    -webkit-transition: all 0.3 ease;
    transition: all 0.3 ease;
    cursor: pointer;
}

.form button:hover,
.form button:active,
.form button:focus {
    background: #43A047;
}

.form .message {
    margin: 15px 0 0;
    color: #b3b3b3;
    font-size: 12px;
}

.form .message a {
    color: #4CAF50;
    text-decoration: none;
}

.form .register-form {
    display: none;
}

.container:before,
.container:after {
    content: "";
    display: block;
    clear: both;
}

.container .info {
    margin: 50px auto;
    text-align: center;
}

.container .info h1 {
    margin: 0 0 15px;
    padding: 0;
    font-size: 36px;
    font-weight: 300;
    color: #1a1a1a;
}

.container .info span {
    color: #4d4d4d;
    font-size: 12px;
}

.container .info span a {
    color: #000000;
    text-decoration: none;
}

.container .info span .fa {
    color: #EF3B3A;
}

</style>


@section('title', "Centro de Salud")
@section('name', "Home")

@extends('layouts.app1')
@yield('sidebar')
@section('content')

<div class="container">
<form action="{{ route('tratamiento.update' , $tratamiento->id) }}" method="POST" enctype="multipart/form-data" >
        @method('PUT')
        {{@csrf_field()}}

        @if (count($errors) > 0)
        <div class="alert alert-danger">
            <div>
                <ul>
                    @foreach ($errors->all() as $message)
                    <h6><error>Error!</strong> {{ $message }}</h6>
                    @endforeach
                </ul>
            </div>
        </div>
        @endif
        <div class="container">
        <div class="login-page">
            <div class="form">
                <h2>Material Tratamiento</h2>
                <form class="register-form">
                    <h4>Imagen</h4>
                    <input type="file" name="imagen"><br>
                    <h4>Palabra</h4>
                    <input type="text" name="palabra" value="{{$tratamiento->palabra}}"><br><br>
                    <h4>Audio</h4>
                    <input type="file" name="audio"><br>
                    <button>Guardar</button>
                </form>

            </div>
        </div>
        </div>
        
    </form>
</div>
@endsection

resources/views/Tratamiento/tratamiento_lista.blade.php
@section('title', "Centro de Salud")
@section('name', "Home")

@extends('layouts.app1')
@yield('sidebar')
@section('content')
<div class="container">
    <br><br>
    <h1>MATERIAL DE TRATAMIENTO</h1>


    <a title="Nuevo Tratamiento" href="tratamiento/create"><img src="/images/tratamiento_nuevo.svg" class="imagenpequeña1"></a>
    <!-- <h5>Crear</h5> -->

    <h5>
        <a title="Nuevo Tratamiento" href="tratamiento/create">Crear Tratamiento</a>
    </h5>

    <form>
        <div class="card-body row no-gutters align-items-center">
            <!--end of col-->
            <div class="col">
                <input class="form-control form-control-lg form-control-borderless" type="search"
                    placeholder="Buscar" name="search" id="search">
            </div>
            <!--end of col-->
            <div class="col-auto">
                <button class="btn btn-lg btn-success" type="submit">Buscar</button>
            </div>
            <!--end of col-->
        </div>
    </form>

</div>
<div class="table-responsive1">
    <table class="table small">
        <thead>
            <tr class="table-secondary">
            <th>Id</th>
            <th>Imagen</th>
            <th>Palabra</th>
            <th>Audio</th>
            <th>Opciones</th>
            </tr>
        </thead>
        @forelse($tratamientos as $tratamiento)
        <tr>
            <td>{{ $tratamiento->id }}</td>
            <td>{{ $tratamiento->imagen }}</td>
            <td>{{ $tratamiento->palabra }}</td>
            <td>{{ $tratamiento->audio }}</td>
            <td>
                <div class="container">

                    <div class="row justify-content-md-center">
                        <div class="col-">
                        <a title="Editar" href="{{route('tratamiento.edit', $tratamiento->id)}}"><img
                                src="/images/editar.png" class="pequeña"></a>
                        </div>
                        <div class="col-">
                        <form action="{{route('tratamiento.destroy', $tratamiento->id)}}" method="post">
                                @method('delete')
                                @csrf
                                <input title="Eliminar" type=image src="/images/eliminar.png" class="imagenpequeña">
                            </form>
                        </div>
                    </div>
                </div>
            </td>


        </tr>

        @empty


        <h5>No existe tratamientos registrados</h5>

        @endforelse


    </table>
    <div class="paginate">
    {{$tratamientos->render()}}
    </div>

</div>



</div>
@endsection