routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');
Route::get('perfil/informacion_editar',['as'=> 'perfil.edit', 'uses' => 'UsersController@edit']);
Route::put('perfil/informacion_editar',['as'=> 'perfil.update', 'uses' => 'UsersController@update']);
Route::resource('/paciente', 'PacientesController');
route::resource('/usuarios', 'InformacionesController');
Route::resource('/tratamiento', 'TratamientosController');
Route::resource('/evaluacion', 'RegistroController');
Route::get('/tratamiento_lista', 'TratamientosController@tratamiento_lista');
Route::get('paciente/pdfexport/{paciente}', 'PacientesController@pdfexport');
Route::get('evaluacion/pdfexport/{evaluacion}', 'RegistroController@pdfexport');


// PDF

// Route::get('pdf', function() {
//     $users = App\Paciente::find($id);
//     $pdf = PDF::loadview('ejemplo', ['paciente' => $users]);
//     return $pdf->download('ejemplo.pdf');
// });

app/Paciente.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

class Paciente extends Model
{
    // Padre - hijo
    public function registros()
    {
        return $this->hasMany('App\Paciente', 'id_p', 'id');
    }

    // hijo - padre
    public function users(){
        return $this->belongsTo('App\User', 'id_u', 'id');
    }

    public function miembros(){
        // return $this->belongsToMany('User','id_p', 'id');
        return $this->hasMany('App\Miembro','id_p', 'id');
    }
    
    protected $fillable =[
        'nombre','id_u', 'f_nacimiento','edad','direccion','telefono','referencia','motivo','fonacion','lenguaje','habla','audicion','otro','n_madre','e_madre','o_madre','n_padre','e_padre','o_padre','observacion','recomendacion','conclusion',];
    
        public function scopeName($query, $name){
            if(trim($name)!=""){
                $query->where('nombre', "LIKE", "%$name%");
                }
            }
        }

app/Http/Controllers/PacientesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Paciente;
use App\User;
use App\Miembro;
use PDF;

class PacientesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $pacientes = Paciente::name($request->get('search'))->with('users')->where('id_u', Auth::id())->paginate(5);
        // $tratamientos= Terapia::name($request->get('search'))->orderBy('id','DESC')
        // ->paginate(2);
        $title = "Listado de Registros";
        return view('Pacientes/paciente_lista', compact('title', 'pacientes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('Pacientes/paciente_crear');
    }

    protected function validator(array $data)
    { 
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $rules= [
             'nombre' => 'required',
             'f_nacimiento' => 'required',
             'edad' => 'required|integer',
             'referencia' => 'required',
             'motivo' => 'required',
             'telefono' => 'numeric',
             'fonacion' => 'max:2',
             'lenguaje' => 'max:2',
             'habla' => 'max:2',
             'audicion' => 'max:2',
         ];

      
        $this->validate($request, $rules);

        $mensaje = new Paciente();
        $mensaje->nombre = $request->nombre; // base de datos - formulario
        $mensaje->f_nacimiento = $request->f_nacimiento;
        $mensaje->edad = $request->edad;
        $mensaje->direccion = $request->direccion;
        $mensaje->telefono = $request->telefono;
        $mensaje->referencia = $request->referencia;
        $mensaje->motivo = $request->motivo;
        $mensaje->fonacion = $request->fonacion;
        $mensaje->lenguaje = $request->lenguaje;
        $mensaje->habla = $request->habla;
        $mensaje->audicion = $request->audicion;
        $mensaje->otro = $request->otro;
        $mensaje->n_madre = $request->n_madre;
        $mensaje->e_madre = $request->e_madre;
        $mensaje->o_madre = $request->o_madre;
        $mensaje->n_padre = $request->n_padre;
        $mensaje->e_padre = $request->e_padre;
        $mensaje->o_padre = $request->o_padre;
        $mensaje->id_u = Auth::user()->id;

        $mensaje->observacion = $request->observacion;
        $mensaje->recomendacion = $request->recomendacion;
        $mensaje->conclusion = $request->conclusion;
        
        $miembros = $request->all()['miembros'];

        if($mensaje->save()){
            foreach($miembros as $miembro){
                    $miembro['id_p'] = $mensaje->id;
                Miembro::create($miembro);   
            }
        return redirect()->route('paciente.index')->with('exito',"REGISTRO GUARDADO EXITOSAMENTE");
        }else{
            return redirect()->route('paciente.index')->with('error',"ERROR AL GUARDAR UN PACIENTE");
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Paciente $paciente)
    {
            return view('Pacientes/paciente_show', compact('paciente'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, Paciente $paciente)
    {
        $paciente = Paciente::with('miembros')->where('id', $paciente->id)->get();

        if (count($paciente) >= 1) {
            $paciente = $paciente[0];
        }
        
        $miembros = Miembro::all();     
        return view('Pacientes/paciente_editar', compact('paciente', 'miembros'));
        
        // return view('Pacientes/paciente_editar', compact('paciente'))->with('pacientes');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Paciente $paciente)
    {
        // dd($paciente);
        // dd($request);

        $rules= [
            'nombre' => 'required',
            'f_nacimiento' => 'required',
            'edad' => 'required|integer',
            'motivo' => 'required',
            'telefono' => 'numeric',
            'fonacion' => 'max:2',
            'lenguaje' => 'max:2',
            'habla' => 'max:2',
            'audicion' => 'max:2',
        ];

     
       $this->validate($request, $rules);
        
        $paciente->nombre = $request->nombre; // base de datos - formulario
        $paciente->f_nacimiento = $request->f_nacimiento;
        $paciente->edad = $request->edad;
        $paciente->direccion = $request->direccion;
        $paciente->telefono = $request->telefono;
        $paciente->referencia = $request->referencia;
        $paciente->motivo = $request->motivo;
        $paciente->fonacion = $request->fonacion;
        $paciente->lenguaje = $request->lenguaje;
        $paciente->habla = $request->habla;
        $paciente->audicion = $request->audicion;
        $paciente->otro = $request->otro;
        $paciente->n_madre = $request->n_madre;
        $paciente->e_madre = $request->e_madre;
        $paciente->o_madre = $request->o_madre;
        $paciente->n_padre = $request->n_padre;
        $paciente->e_padre = $request->e_padre;
        $paciente->o_padre = $request->o_padre;
        

        $paciente->observacion = $request->observacion;
        $paciente->recomendacion = $request->recomendacion;
        $paciente->conclusion = $request->conclusion;
    
        // if($paciente->update()){
        // return redirect()->route('paciente.index')->with('exito',"REGISTRO GUARDADO EXITOSAMENTE");
        // }else{
        //     return redirect()->route('paciente.index')->with('error',"ERROR AL GUARDAR UN PACIENTE");
        // }
         $paciente->update();
         $paciente->miembros()->delete();//Miembro::where('id_p', $paciente->id)->delete();
         $miembros = $request->input('miembros', []);
          
         foreach($miembros as $miembro){
            $miembro['id_p'] = $paciente->id;
            Miembro::create($miembro);   
        }
        return redirect()->route('paciente.index')->with('exito',"REGISTRO GUARDADO EXITOSAMENTE");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    { 
        $paciente = Paciente::find($id)->delete();
        return redirect()->route('paciente.index')->with('exito',"Eliminado Exitoso");

        // $pacientes = DB::table('pacientes')->get();
        // $title = "Listado de Registros";

        // return view('Pacientes/paciente_lista', compact('title', 'pacientes'));

        // if($id->delete()){
        //     return redirect()->route('paciente.index')->with('exito',"REGISTRO GUARDADO EXITOSAMENTE");
        //     }else{
        //         return redirect()->route('paciente.index')->with('error',"ERROR AL GUARDAR UN PACIENTE");
        //     }

    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function pdfexport(Request $request, Paciente $paciente){

        
        // $paciente = Paciente::find($id);
        $paciente = Paciente::with('miembros')->where('id', $paciente->id)->get();

        if (count($paciente) >= 1) {
            $paciente = $paciente[0];
        }
        $miembros = Miembro::all();
        
        $pdf = \App::make('dompdf.wrapper');
        /* Careful: use "enable_php" option only with local html & script tags you control.
        used with remote html or scripts is a major security problem (remote php injection) */
        $pdf->getDomPDF()->set_option("enable_php", true);
        $pdf = PDF::loadView('Pacientes\pdf', compact('paciente', 'miembros'));
        // $pdf = PDF::loadView('Pacientes\pdf', ['paciente' => $paciente]);
       
        $fileName = $paciente->name;
        $fileName = $paciente->f_nacimiento;
        $fileName = $paciente->edad;
        $fileName = $paciente->direccion;
        $fileName = $paciente->telefono;
        $fileName = $paciente->referencia;
        $fileName = $paciente->motivo;
        $fileName = $paciente->fonacion;
        $fileName = $paciente->lenguaje;
        $fileName = $paciente->habla;
        $fileName = $paciente->audicion;
        $fileName = $paciente->otro;
        $fileName = $paciente->n_madre;
        $fileName = $paciente->e_madre;
        $fileName = $paciente->o_madre;
        $fileName = $paciente->n_padre;
        $fileName = $paciente->e_padre;
        $fileName = $paciente->o_padre;


        $fileName = $paciente->observacion;
        $fileName = $paciente->recomendacion;
        $fileName = $paciente->conclusion;
        

        return $pdf->stream();
    }
}

resources/views/Pacientes/paciente_crear.blade.php
<script src="http://code.jquery.com/jquery-latest.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    /**
     * Funcion para añadir una nueva fila en la tabla
     */
    var cont = 0;
    $("#add").click(function() {
        cont++;
        var nuevaFila = "<tr> \
			  //<td><input type='text' name='miembros[" + cont + "][m_casa]'></td> \
                <td><input type='text' name='miembros[" + cont + "][m_edad]'></td> \
                <td><input type='text' name='miembros[" + cont + "][m_sexo]'></td> \
                <td><input type='text' name='miembros[" + cont + "][m_relniño]'></td> \
				<td><input type='button' class='del' value='Eliminar'></td> \
			</tr>";
        $("#tabla tbody").append(nuevaFila);
    });

    // evento para eliminar la fila
    $("#tabla").on("click", ".del", function() {
        $(this).parents("tr").remove();
    });

    $("#add").click();
});
</script>

<style>
.error {
    color: #D8000C;
    background-color: #FFBABA;
    background-image: url('imagenes/error.jpg');
}
h5{

}

</style>
@section('title', "Centro de Salud")
@section('name', "Home")


@extends('layouts.app1')

@yield('sidebar')
@section('content')

@include('Plantilla.tabla')
<div>
    <br><br>
    <div class="container">
        <form action="{{ route('paciente.store') }}" method="POST">
            @method('post')
            @csrf
            <h1>REGISTRO DE PACIENTE</h1>


            
            @if (count($errors) > 0)


            <div class="alert alert-danger">
                <div>
                    <ul>
                        @foreach ($errors->all() as $message)
                        <h6><error>Error!</strong> {{ $message }}</h6>
                        @endforeach
                    </ul>
                </div>
            </div>
            @endif

            <div class="form-row">
                <div class="col-7">

                    <input type="text" name="nombre" class="form-control" placeholder="Nombre del Paciente">
                </div>
                <div class="col">
                    <input type="date" name="f_nacimiento" class="form-control" placeholder="Fecha de Nacimiento">
                </div>
                <div class="col-">
                    <input type="text" name="edad" class="form-control" placeholder="Edad Cronológica">
                </div>
            </div>


            <div class="form-row">
                <div class="col-7">
                    <input type="text" name="direccion" class="form-control" placeholder="Dirección del Paciente">
                </div>
                <div class="col">
                    <input type="int" name="telefono" class="form-control" placeholder="Teléfono del Paciente">
                </div>
                <div class="col">
                    <input type="hidden">
                </div>
            </div>

            <div class="form-row">
                <div class="col-7">
                    <input type="text" name="referencia" class="form-control"
                        placeholder="Persona o Institución que le refirió al Centro">
                </div>
                <div class="col">
                    <input type="int" name="motivo" class="form-control" placeholder="Motivo de la Consulta">
                </div>
            </div><br>



            <h5>PACIENTE REFERIDO AL PROBLEMA</h5>
            <div class="form-row">
                <div class="col-">
                    <input type="text" name="fonacion" class="form-control" placeholder="Fonación">
                </div>
                <div class="col-">
                    <input type="int" name="lenguaje" class="form-control" placeholder="Lenguaje">
                </div>
                <div class="col-">
                    <input type="text" name="habla" class="form-control" placeholder="Habla">
                </div>
                <div class="col-">
                    <input type="int" name="audicion" class="form-control" placeholder="Audición">
                </div>
                <div class="col">
                    <input type="int" name="otro" class="form-control" placeholder="Otro">
                </div>
            </div><br>




            <h5>DATOS DE LOS PADRES</h5>

            <div class="form-row">
                <div class="col-7">
                    <input type="text" name="n_padre" class="form-control" placeholder="Nombre del Papá">
                </div>
                <div class="col-">
                    <input type="text" name="e_padre" class="form-control" placeholder="Edad del Papá">
                </div>
                <div class="col">
                    <input type="text" name="o_padre" class="form-control" placeholder="Profesión del Papá">
                </div>
            </div>

            <div class="form-row">
                <div class="col-7">
                    <input type="text" name="n_madre" class="form-control" placeholder="Nombre de la Mamá">
                </div>
                <div class="col-">
                    <input type="text" name="e_madre" class="form-control" placeholder="Edad de la Mamá">
                </div>
                <div class="col">
                    <input type="text" name="o_madre" class="form-control" placeholder="Profesión de la Mamá">
                </div>
            </div><br>


            <table id="tabla" class="tabla">
                <caption>Miembros de Familia</caption>
                <thead>
                    <tr>
                        <!-- <th>Cedula</th> -->
                        <th>Nombre</th>
                        <th>Edad</th>
                        <th>Sexo</th>
                        <th>Relación</th>

                        <th><input type="button" id="add" value="Añadir"></th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table><br>


            <div class="form-row">
                <div class="col">
                    <input type="int" name="observacion" class="form-control" placeholder="Observación">
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <input type="int" name="recomendacion" class="form-control" placeholder="Recomendación">
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <input type="int" name="conclusion" class="form-control" placeholder="Conclusión">
                </div>
            </div>
            
            <div class="contenedor">
                <br>
                <div class="row justify-content-md-center">
                    <div class="col-4">
                        <input title="GUARDAR" type=image src="/images/guardar.png" width="50" height="50"
                            class="imagenpequeña">
                        <h5>Guardar</h5>

                    </div>
                    <div class="col-4">
                        <a title="CANCELAR" href="/paciente"><img src="/images/cancelar.png" class="pequeña"></a>
                        <h5>Cancelar</h5>
                    </div>
                </div>
        </form>
    </div>
</div>



</div>
@endsection

resources/views/Pacientes/paciente_editar.blade.php
<script src="http://code.jquery.com/jquery-latest.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    /**
     * Funcion para añadir una nueva fila en la tabla
     */
     var cont=0;

    var jsonPaciente = {!! json_encode($paciente->toArray(), JSON_HEX_TAG) !!}
    cont = jsonPaciente.miembros.length;

    $("#add").click(function() {
        console.log(cont);
        cont++;
        var nuevaFila = "<tr> \
                <input type='hidden' name='miembros[" + cont + "][id]' value=''>  \
                <td><input type='text' name='miembros[" + cont + "][m_casa]'></td> \
                <td><input type='text' name='miembros[" + cont + "][m_edad]'></td> \
                <td><input type='text' name='miembros[" + cont + "][m_sexo]'></td> \
                <td><input type='text' name='miembros[" + cont + "][m_relniño]'></td> \
				<td><input type='button' class='del' value='Eliminar Fila'></td> \
			</tr>";
        $("#tabla tbody").append(nuevaFila);
    });

    // evento para eliminar la fila
    $("#tabla").on("click", ".del", function() {
        $(this).parents("tr").remove();
    });
});
</script>

@section('title', "Centro de Salud")
@section('name', "Home")


@extends('layouts.app1')

@yield('sidebar')
@section('content')

@include('Plantilla.tabla')
<div>
    
    <div class="container">
    <br><br>
    <form action="{{ route('paciente.update', $paciente->id) }}" method="POST">
        @method('put')
        @csrf
            <h1>EDICIÓN DE PACIENTE</h1>


            @if (count($errors) > 0)


            <div class="alert alert-danger">
                <div>
                    <ul>
                        @foreach ($errors->all() as $message)
                        <h6><error>Error!</strong> {{ $message }}</h6>
                        @endforeach
                    </ul>
                </div>
            </div>
            @endif

            <div class="form-row">
                <div class="col-7">
                    <input type="text" value="{{$paciente->nombre}}" name="nombre" class="form-control" placeholder="Nombre del Paciente">
                </div>
                <div class="col">
                    <input type="date" value="{{$paciente->f_nacimiento}}" name="f_nacimiento" class="form-control" placeholder="Fecha de Nacimiento">
                </div>
                <div class="col-">
                    <input type="text" value="{{$paciente->edad}}" name="edad" class="form-control" placeholder="Edad Cronologica">
                </div>
            </div>


            <div class="form-row">
                <div class="col-7">
                    <input type="text" value="{{$paciente->direccion}}" name="direccion" class="form-control" placeholder="Dirección del Paciente">
                </div>
                <div class="col">
                    <input type="int" value="{{$paciente->telefono}}" name="telefono" class="form-control" placeholder="Teléfono del Paciente">
                </div>
                <div class="col">
                    <input type="hidden">
                </div>
            </div>

            <div class="form-row">
                <div class="col-7">
                    <input type="text" value="{{$paciente->referencia}}" name="referencia" class="form-control"
                        placeholder="Persona o Institución que le refirió el Centro">
                </div>
                <div class="col">
                    <input type="int" value="{{$paciente->motivo}}" name="motivo" class="form-control" placeholder="Motivo de la Consulta">
                </div>
            </div><br>



            <h5>PACIENTE REFERIDO AL PROBLEMA</h5>
            <div class="form-row">
                <div class="col-">
                    <input type="text" value="{{$paciente->fonacion}}" name="fonacion" class="form-control" placeholder="Fonación">
                </div>
                <div class="col-">
                    <input type="int" value="{{$paciente->lenguaje}}" name="lenguaje" class="form-control" placeholder="Lenguaje">
                </div>
                <div class="col-">
                    <input type="text" value="{{$paciente->habla}}" name="habla" class="form-control" placeholder="Habla">
                </div>
                <div class="col-">
                    <input type="int" value="{{$paciente->audicion}}" name="audicion" class="form-control" placeholder="Audición">
                </div>
                <div class="col">
                    <input type="int" value="{{$paciente->otro}}" name="otro" class="form-control" placeholder="Otro">
                </div>
            </div><br>




            <h5>DATOS DE LOS PADRES</h5>

            <div class="form-row">
                <div class="col-7">
                    <input type="text" value="{{$paciente->n_padre}}" name="n_padre" class="form-control" placeholder="Nombre del Papá">
                </div>
                <div class="col-">
                    <input type="text" value="{{$paciente->e_padre}}" name="e_padre" class="form-control" placeholder="Edad del Papá">
                </div>
                <div class="col">
                    <input type="text" value="{{$paciente->o_padre}}" name="o_padre" class="form-control" placeholder="Profesión del Papá">
                </div>
            </div>

            <div class="form-row">
                <div class="col-7">
                    <input type="text" value="{{$paciente->n_madre}}" name="n_madre" class="form-control" placeholder="Nombre del Mamá">
                </div>
                <div class="col-">
                    <input type="text" value="{{$paciente->e_madre}}" name="e_madre" class="form-control" placeholder="Edad del Mamá">
                </div>
                <div class="col">
                    <input type="text" value="{{$paciente->o_madre}}" name="o_madre" class="form-control" placeholder="Profesión del Mamá">
                </div>
            </div><br>


            <table id="tabla" class="tabla">
                <caption>Miembros de Familia</caption>
                <thead>
                    <tr>
                        <!-- <th>Cedula</th> -->
                        <th>Nombre</th>
                        <th>Edad</th>
                        <th>Sexo</th>
                        <th>Relación</th>

                        <th><input type="button" id="add" value="Añadir"></th>
                    </tr>
                </thead>
                <tbody>
                @foreach($paciente->miembros as $miembro)
                <tr>
                    <td>
                        <input type='hidden' name='miembros[{{$loop->index }}][id]' value="{{$miembro->id}}" class="x">
                        <input  type='text' name='miembros[{{$loop->index }}][m_casa]' value="{{$miembro->m_casa}}">
                    </td>
                    <td><input  type='text' name='miembros[{{$loop->index }}][m_edad]' value="{{$miembro->m_edad}}"></td>
                    <td><input  type='text' name='miembros[{{$loop->index }}][m_sexo]' value="{{$miembro->m_sexo}}"></td>
                    <td><input  type='text' name='miembros[{{$loop->index }}][m_relniño]' value="{{$miembro->m_relniño}}"></td>
                    <td><input  type='button' class='del' value='Eliminar Fila'></td>
                </tr>
            @endforeach
                </tbody>
            </table><br>


            <div class="form-row ">
                <div class="col">
                    <input type="int" value="{{$paciente->observacion}}" name="observacion" class="form-control" placeholder="Observación">
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <input type="int" value="{{$paciente->recomendacion}}" name="recomendacion" class="form-control" placeholder="Recomendación">
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <input type="int" value="{{$paciente->conclusion}}" name="conclusion" class="form-control" placeholder="Conclusión">
                </div>
            </div>

            <div class="contenedor">
                <br>
                <div class="row justify-content-md-center">
                    <div class="col-4">
                        <input title="GUARDAR" type=image src="/images/guardar.png" width="50" height="50"
                            class="imagenpequeña">
                        <h5>Guardar</h5>

                    </div>
                    <div class="col-4">
                        <a title="CANCELAR" href="/paciente"><img src="/images/cancelar.png" class="pequeña"></a>
                        <h5>Cancelar</h5>
                    </div>
                </div>

        </form>
    </div>


</div>
@endsection

resources/views/Pacientes/paciente_lista.blade.php
@section('title', "Centro de Salud")
@section('name', "Home")

@extends('layouts.app1')
@yield('sidebar')
@section('content')
<style>

</style>
<div class="container">
    <br><br>
    <h1>LISTADO DE PACIENTES</h1>


    <a title="Nuevo Paciente" href="{{ route('paciente.create')}}"><img src="/images/nuevo1.png" class="imagenpequeña1"></a>
    <!-- <h5>Crear Paciente</h5> -->

    <h5>
        <a title="Nuevo Paciente" href="{{ route('paciente.create')}}">Crear Paciente</a>
    </h5>

    <form>
        <div class="card-body row no-gutters align-items-center">
            <!--e   nd of col-->
            <div class="col">
                <input class="form-control form-control-lg form-control-borderless" type="search"
                    placeholder="Buscar" name="search" id="search">
            </div>
            <!--end of col-->
            <div class="col-auto">
                <button class="btn btn-lg btn-success" type="submit">Buscar</button>
            </div>
            <!--end of col-->
        </div>
    </form>

</div><br>
<div class="table-responsive1">
    <table class="table small">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Edad</th>
                <th>Teléfono</th>
                <th>Motivo</th>
                <th>Opciones</th>
            </tr>
        </thead>
        @forelse($pacientes as $paciente)
        <tr>
            <td>{{ $paciente->id }}</td>
            <td>{{ $paciente->nombre }}</td>
            <td>{{ $paciente->edad }}</td>
            <td>{{ $paciente->telefono }}</td>
            <td>{{ $paciente->motivo }}</td>
            <td>
                <div class="container">

                    <div class="row justify-content-md-center">
                        <div class="col-">
                            <a title="Editar" href="{{route('paciente.edit', $paciente->id)}}"><img
                                    src="/images/editar.png" class="pequeña"></a>
                        </div>
                        <div class="col-">
                            <a title="PDF" href="{{ url('paciente/pdfexport/' . $paciente->id)}}" target="_blank"><img
                                    src="/images/pdf.png" class="pequeña"></a>
                        </div>
                        <div class="col-">
                        
                            <form action="{{route('paciente.destroy', $paciente->id)}}" method="post">
                                @method('delete')
                                @csrf
                                
                                <input title="Eliminar" type=image src="/images/eliminar.png" width="50" height="50"
                                    class="imagenpequeña"> </form>
                        </div>
                    </div>
                </div>
            </td>


        </tr>

        @empty


        <h5>No existe pacientes registrados</h5>

        @endforelse


    </table>
    <div class="paginate">
    {!!$pacientes->render()!!}

    </div>

</div>



</div>
@endsection